[build]
# Użyj wszystkich dostępnych rdzeni procesora
# jobs = 8

# Konfiguracja dla Windows
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+crt-static"
]

# Konfiguracja dla Linux
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "target-cpu=native"
]

# Konfiguracja dla macOS
[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]

# Alias dla częstych komend
[alias]
b = "build"
c = "check"
r = "run"
t = "test"
fast = "build --profile dev-fast"
release-dbg = "build --profile release-with-debug"

# Konfiguracja cargo-watch (jeśli używasz)
[env]
RUST_BACKTRACE = { value = "1", condition = { env-not-set = "RUST_BACKTRACE" } }