import { HorizontalBox } from "std-widgets.slint";
import { Kolory } from "colors.slint";

import "../resources/fonts/Geist-Regular.otf";
import "../resources/fonts/Geist-Bold.otf";
import "../resources/fonts/GeistMono-Regular.otf";

export component DraggableWindow {
    in-out property <string> window-title: "";
    callback exit(); // For closing the window
    callback dragged(length, length);
    callback drag-ended();
    in-out property <bool> is-dragging-active: false;

    // Drag Handle
    Rectangle {
        height: 20px;
        background: Kolory.hover;

        TouchArea {
            width: parent.width;
            height: parent.height;
            mouse-cursor: move;
            moved => {
                if (self.pressed) {
                    if (!root.is-dragging-active) {
                        root.is-dragging-active = true;
                    }
                    root.dragged(self.mouse-x - self.pressed-x, self.mouse-y - self.pressed-y);
                } else {
                    if (root.is-dragging-active) {
                        root.is-dragging-active = false;
                        root.drag-ended();
                    }
                }
            }
            clicked => {
                if (root.is-dragging-active) {
                    root.is-dragging-active = false;
                    root.drag-ended();
                }
            }

            HorizontalBox {
                padding: 0px;
                spacing: 0px;
                alignment: stretch;

                // Window Title
                Rectangle { width: 5px; background: transparent; }
                Text {
                    text: root.window-title;
                    color: Kolory.tekst_silny;
                    font-size: 10px;
                    font-family: "Geist";
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }

                // Spacer to push X to the right
                Rectangle {
                    horizontal-stretch: 1;
                    background: transparent;
                }

                // Close Button
                Rectangle {
                    width: 20px;
                    height: parent.height;
                    background: close-button-area.has-hover ? Kolory.obramowanie : transparent;

                    Text {
                        text: "×";
                        color: Kolory.tekst_silny;
                        font-size: 16px;
                        font-family: "Geist";
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }

                    close-button-area := TouchArea {
                        width: parent.width;
                        height: parent.height;
                        clicked => { root.exit(); }
                    }
                }
            }
        }
    }
}