export global Kolory {
    // Podstawowe tła i obramowania
    out property <color> tlo: #242532;
    out property <color> obramowanie: #1e1f28;
    out property <color> hover: #f4971d;

    // Teksty
    out property <color> tekst: #cccccc;
    out property <color> tekst_silny: #ffffff;
    out property <color> tekst_slabszy: #aaaaaa;

    // Panele i linie podziału
    out property <color> panel_tlo: #2f313e;
    out property <color> linia_podzialu: #1e1f28;

    // Menu i zakładki
    out property <color> menu_tlo: #242532;
    out property <color> menu_obramowanie: #1e1f28;
    out property <color> zakladka_tlo: #2f313e;
    out property <color> zakladka_obramowanie: #1e1f28;
    out property <color> zakladka_aktywna_tlo: #242532;
    out property <color> zakladka_aktywna_obramowanie: #1e1f28;

    // Konsola
    out property <color> konsola_tlo: #2f313e;

    // Suwaki
    out property <color> suwak_tlo: #242532;
    out property <color> suwak_tor: #606060;
    out property <color> ekspozycja_galka: #242532;
    out property <color> ekspozycja_galka_hover: #8080ff;
    out property <color> gamma_galka: #242532;
    out property <color> gamma_galka_hover: #ff8080;
    // Pasek postępu
    out property <color> progress_fill: #af4cac;

    // Kanały
    out property <color> kanal_r: #ff8181;
    out property <color> kanal_g: #b0ffb0;
    out property <color> kanal_b: #92d2ff;

    // Inne
    out property <color> przezroczysty: transparent;
}


